### ISSUE TITLE
Treats the constant function as non-monotonic

### ISSUE THREAD

**Issue by NoahDReifsnyder** [alvarosg/pynverse#4]
Currently treats a lambda function that returns a constant value, i.e. lambda x: 1, as a non-monotonic function and returns an error.

**Comment by alvarosg** [comment]
Thank you for your message, indeed the constant function is not strictly monotonic, and does not have an inverse, so I think this is working as intended :)

**Comment by NoahDReifsnyder** [comment]
You know, never really realized that. The inverse of the constant function is indeed not a function. Haha thanks for the response!
