### ISSUE TITLE
AttributeError:module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by XipengYu** [alvarosg/pynverse#5]
if numpy version is equal to 1.24.2, then will retrun AttributeError:module 'numpy' has no attribute 'bool'.
`cube = (lambda x: x**3)`
`invcube = inversefunc(cube, y_values=27)`

FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  resultsmask = np.zeros(yin.shape, dtype=np.bool)
AttributeError:  module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.

**Comment by alvarosg** [comment]
Thanks! would you mind submitting a pull request for this?
