### ISSUE TITLE
Apologies for the unrelated issue - Requesting dataset access for replicating "Learning to Simulate Complex Physics with Graph Networks" paper

### ISSUE THREAD

**Issue by ecent2000** [alvarosg/pynverse#8]
Dear Alvaro Sanchez Gonzalez,

First of all, I sincerely apologize for posting an issue here that is not directly related to this specific project repository. I attempted to find your contact information to reach out directly, but unfortunately was unsuccessful.

I am a student currently working on my thesis, and I am very interested in referencing and reproducing the excellent work from your paper "Learning to Simulate Complex Physics with Graph Networks". Your research is highly relevant and valuable to my own work.

However, when trying to replicate the experiments, I discovered that the datasets used in the paper do not seem to be accessible from the official code repository at https://github.com/deepmind/deepmind-research/tree/master/learning_to_simulate.

I was hoping that you might be willing to share the original datasets used in your paper. Having access to this data is crucial for me to be able to faithfully replicate your methodology and build upon your work.

If you are able to assist, it would be greatly appreciated if you could send the datasets to my email address: bobbot740@gmail.com.

Thank you very much for your understanding, and once again, I apologize for the inconvenience of this unrelated issue. Any help you could provide in sharing the datasets would be immensely appreciated.

Best regards,

ecent

**Comment by alvarosg** [comment]
Thanks, I have replied and subscribed to the  issue created in the correct repo. Closing this one.
